### PR TITLE
Add extra missing lichess board themes.

### PR DESCRIPTION
**Pull request by greatwolf**
This PR adds the missing lichess.org board themes to the mobile app. This goes towards addressing #1230 and #1231 as requested by other users.

### CODE REVIEW

**Comment by Ejstn** [comment]
Awesome, thanks!

**Comment by veloce** [comment]
Many thanks for this @greatwolf . Though, I am sorry, as I won't be able to merge your PR as is. The thing is that I don't want to add that many boards to the app package, as I try to keep it light. I have already a basis to download themes and save them to the app and I have some local work (not pushed yet) already done to do the same for boards.
But what you did here will be useful nevertheless, especially the css file, so I'll try to integrate your commit in my branch.

**Comment by greatwolf** [comment]
sure thing.

**Comment by veloce** [comment]
One PR per piece set is fine yes. Pieces are svg so it's much lighter, so I don't plan to remove pieces from the package for now.

**Comment by LichessUser** [comment]
So you mean you will add new piece sets and won't remove any elder one as they are really lite?

**Pull request merged**
