### PR TITLE
fix typescript imports

### PR DESCRIPTION
**Pull request by vdebergue**
This will make the project compiles correctly with typescript. 

I haven't tested the application yet (it takes some time to configure android ^^)

### CODE REVIEW

**Comment by veloce** [comment]
awesome man! :)

I can help you to build the app if you need.

**Comment by veloce** [comment]
Or you can just test it with `gulp watch` and the browser.

**Comment by vdebergue** [comment]
If you are @zen tomorrow we can have a look. I didn't manage to turn off chrome security on osx. Will need some more time to figure it out

**Comment by veloce** [comment]
Ok let's do this. I'll add the security stuff in the readme because a lot of people have asked me about it.

**Pull request merged**
