### PR TITLE
Added 'cardinal' piece set from lichess site.

### PR DESCRIPTION
**Pull request by greatwolf**
This adds the missing cardinal piece set as requested in #1231.

### CODE REVIEW

**Comment by LichessUser** [comment]
Thank you GreatWolf, I don't know much about GitHub, Thanks for helping me.

**Comment by LichessUser** [comment]
when will they release the next version?

**Comment by greatwolf** [comment]
I'm not sure, that's really going to be up to @veloce.

If you're on android you can just fork this and use travis to build and deploy it without needing to download a whole android studio dev environment on your machine. See my branch [`mybuild_config`](https://github.com/greatwolf/lichobile/tree/mybuild_config) in my fork. Once you get the app-release.apk you can manually sideload it with `adb install app-release.apk`

**Comment by LichessUser** [comment]
How to get app_release.apk, can you give me the link?

**Pull request merged**
