### PR TITLE
Update & improve italian translation

### PR DESCRIPTION
**Pull request by renyhp**
Most of the changes proposed here are consistent to what is already on the site via Crowdin.

### CODE REVIEW

**Comment by jas14** [comment]
@renyhp , how have you been dealing with editing the single-line JSON translation blob? Asking as I'm trying to localize a few more strings.

**Comment by renyhp** [comment]
@jas14 it's been quite some time ago so I can't remember the exact way I have done it, probably used Visual Studio which formatted it automatically in a readable way. Anyway googling "JSON formatter" gives you a lot of possibilities, I have just found [this website](https://jsonformatter.curiousconcept.com/) which will surely do the job. As for maybe putting the JSON in place in a single line, probably just searching for tabs and newlines and replacing with nothing will do the trick.

Anyway I don't see much interest in this kind of PR (which is quite reasonable since it seems there are plans to switch to the Crowdin translations), so probably it's not worth the effort. If you want to contribute to translation I would suggest you do that [directly in Crowdin](https://crowdin.com/project/lichess).

**Comment by jas14** [comment]
Any pointers to conversation(s) on switching to Crowdin? Seems like a great solution, I'd love to follow along on progress (and/or contribute)!

**Comment by renyhp** [comment]
There's no actual conversation going on but the relevant issues are #639 and #898.


-------- Messaggio originale --------
Oggetto: Re: [veloce/lichobile] Update & improve italian translation (#901)
Da: Joe Stein
A: veloce/lichobile
CC: renyhp ,Mention



Any pointers to conversation(s) on switching to Crowdin? Seems like a great solution, I'd love to follow along on progress (and/or contribute)!

**Pull request closed without merging**
