### PR TITLE
RFC: Migrate from TSLint to ESLint

### LINKED ISSUE #1467: Migrate to ESLint from TSLint?
Palantir, the maintainer of TSLint, [announced](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) in Feb 2019 that TSLint is deprecated in favor of ESLint. The latter will have better continued support, so it may be worth switching.

### PR DESCRIPTION
**Pull request by jas14**
Closes #1467.

The linters can be configured to have different warnings levels, enforced styles, or can be disabled completely. If you'd like to see what linters raised errors initially, check out 
cf26093 and run `npx eslint src/ --quiet`.

Lastly, there are still tons of warnings, which don't currently cause linting to fail but will appear in `npm run lint` output and should be incrementally addressed in the future.

### CODE REVIEW

**Comment by veloce** [comment]
Whaa! Many thanks for this!! And thanks for the added test. I think I'll merge it as is. The only changes that I fear a little are the regex escape changes since the regex were working well with the escape. So I'm gonna test that first then merge it.

**Comment by veloce** [comment]
Oh, before merging the travis build needs to be fixed. Looks like the new backoff test doesn't pass here.

**Comment by jas14** [comment]
Just fixed locally and should pass CI. As for the ["unnecessary escaping"](https://eslint.org/docs/rules/no-useless-escape) fixes in regexes, I can downgrade that error to a warning - just let me know.

**Comment by veloce** [comment]
Many thanks again @jas14

**Pull request merged**
