### PR TITLE
[WIP] Say 'bye' when leaving a game so other player can claim victory

### PR DESCRIPTION
**Pull request by freefal**
Closes https://github.com/veloce/lichobile/issues/424

### CODE REVIEW

**Comment by veloce** [comment]
I think this is not enough: we should also handle the case when user puts app in background, or closes the app.

**Comment by veloce** [comment]
@freefal to do that you need to hook in `pause` cordova event. We use already the `resume` handler in OnlineRound.ts so you have an example.

**Comment by freefal** [comment]
Ok, thanks for the tip.

**Comment by freefal** [comment]
Hmmm...the asynchronous nature of webworkers doesn't easily facilitate our desire to guarantee that the 'bye' message gets sent before the 'pause' event finishes. Need to think about how to get 'pause' to wait for the 'bye' message to get sent or implement another way.

**Comment by veloce** [comment]
Done it here: https://github.com/veloce/lichobile/commit/126cc3ae50101caaa1de59f6a5ea265b8c0ea541

**Comment by Happy0** [comment]
yayyy

**Pull request closed without merging**
