### PR TITLE
add color select for game seek

### PR DESCRIPTION
**Pull request by madnight**
Hi i simply added color select like this:

since i'm new to your application: does it work this way?

Im not sure how to test properly but i tested it on the live system
<pre><code>window.lichess = {
        apiEndPoint: "https://en.lichess.org",
        socketEndPoint: "wss://socket.lichess.org",
        mode: "dev",
      };</code></pre>
and it works there : )

### CODE REVIEW

**Comment by flugsio** [comment]
Color selection is not available for exotic variants in rated games, only casual. Antichess, Atomic, Horde, Racing Kings

**Comment by madnight** [comment]
ok how about adding color selection only for the variant Standard?

**Comment by ornicar** [comment]
I vote :-1:, random color is an excellent default value, and the UI is cluttered already.

**Comment by madnight** [comment]
Well its really annoying that you cant choose the color in the app, i dont understand why the app should miss such a basic features. If im quite honest this missing features was the main reason why i coudn't use the app in many cases, because players want to try openings for black or white and therefore need to choose the color, otherwise people select random and then always abort if they get the wrong color wich is also very annoying. And this already there for Computer Play so i dont get the UI clutter argument, you basicly make the UI more consistent by adding this feature.

**Pull request closed without merging**
