### PR TITLE
[Android] Fix splash logo ratio, add vector drawables

### PR DESCRIPTION
**Pull request by burnoo**
Fixes incorrect ratio of lichess logo on splash screen (clearly visible on longer screens).

Screens from OnePlus 6T:
| Before  | After     |
| ------ | ------ |
|  |  |

### What have been done in this PR
1. Removed splash png files and added [Android Vector Drawable](https://developer.android.com/guide/topics/graphics/vector-drawable-resources?authuser=1) imported from [here](https://github.com/ornicar/lila/blob/master/public/logo/lichess.svg) for Android 6+ and smaller pngs for Android 5.
2. Used new images with 33,(3)% margin on splash screen (works on landscape too)

### Pros
- correct ratio on all devices
- splash logo in best possible quality

### CODE REVIEW

**Comment by veloce** [comment]
Thanks for that, I'll test it asap. Your last commit induced a build error btw.

**Comment by burnoo** [comment]
It doesn't work on API 21-22 :/, I will try to fix that

**Comment by burnoo** [comment]
@veloce I've added pngs for API 21-22, fixed build error - PR is ready for tests

**Comment by jack-webb** [comment]
Could this be extended to implement #975 & #1366? I was about to start implementation myself until I found this PR. It should be quite simple: Just a matter of using a color resource in `vector_logo.xml`, then adding the corresponding colors in `res/values-night/colors.xml`. I don't mind picking up the work for this if necessary. Thanks!

Dark mode illustrations from Google I/O 2019: https://www.youtube.com/watch?v=OCHEjeLC_UY&t=20m28s

**Pull request merged**
